### PR TITLE
Docs: fix url errors

### PR DESCRIPTION
**Pull request by wangenze267**
Link pointing error in the text

### CODE REVIEW

**Comment by wangenze267** [comment]
https://cn.vuejs.org/guide/essentials/lifecycle.html

**Comment by wangenze267** [comment]
https://cn.vuejs.org/guide/essentials/lifecycle.html#lifecycle-diagram

The cycle of Options Api is displayed after the jump. The url path may be wrong

**Comment by KiritaniAyaka** [comment]
The link target depends on your API preference. You can switch it on the sidebar.

**Comment by wangenze267** [comment]
ok,thanks

**Pull request closed without merging**
