### PR TITLE
Update component-basics.md

### PR DESCRIPTION
**Pull request by wwwK**
fix demo error about slot。

### CODE REVIEW

**Comment by Jinjiang** [comment]
The original version is correct. If you still have questions, it would be better to go to the English doc site to discuss. Thanks.

**Comment by wwwK** [comment]
The original version not slot tag before <strong>。

**Comment by wwwK** [comment]
The original version not slot start tag beform strong tag. the markdown content at 473 line.

**Comment by Justineo** [comment]
L475 is a self-closing slot tag.

**Pull request closed without merging**
